[interfaces]
count = 3
name_template = "Ethernet {{n}}/{{n}}"

[interfaces.template.brief]
template = "config_examples/templates/interface.brief.txt"

[routes]
count = 10

[routes.template.brief]
template = "config_examples/templates/route.brief.txt"

[session.x]
prompt = "boby"
level = 10

[session.y]
prompt = "x"
level = 20

[command.show]
level = 0

[command.show.ip.brief]
template_ref = "interfaces.template.brief"

